// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgGFQGrZSkn9CH0lpz3IIikIKmy2103PU',
    appId: '1:362609573305:web:14ca2ecc30ca2b6e6fca68',
    messagingSenderId: '362609573305',
    projectId: 'xen-bloom',
    authDomain: 'xen-bloom.firebaseapp.com',
    storageBucket: 'xen-bloom.appspot.com',
    measurementId: 'G-5JVCTKTLFZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhzUyMJfIYX3ZJsZNVeRM9IgQPsXh20F4',
    appId: '1:362609573305:android:e016819bfde557256fca68',
    messagingSenderId: '362609573305',
    projectId: 'xen-bloom',
    storageBucket: 'xen-bloom.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzQioWlsh-RHdrS-h2F-_emwbi4UDvFAk',
    appId: '1:362609573305:ios:e1c3f73b575717136fca68',
    messagingSenderId: '362609573305',
    projectId: 'xen-bloom',
    storageBucket: 'xen-bloom.appspot.com',
    iosClientId: '362609573305-bkfp9u0rks6cobp178dqroaml20554vc.apps.googleusercontent.com',
    iosBundleId: 'com.example.xenBloom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzQioWlsh-RHdrS-h2F-_emwbi4UDvFAk',
    appId: '1:362609573305:ios:510eeb8f9393d9e56fca68',
    messagingSenderId: '362609573305',
    projectId: 'xen-bloom',
    storageBucket: 'xen-bloom.appspot.com',
    iosClientId: '362609573305-4q7is262lf26avfsr18j0bkdtl12mv1i.apps.googleusercontent.com',
    iosBundleId: 'com.example.xenBloom.RunnerTests',
  );
}
