name: Deploy Firebase Functions

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Dependencies and Deploy Functions
        run: |
             cd CG_Backend_Functions/functions
             npm install -g firebase-tools
             npm install
             firebase deploy --only functions
             

     
